
### Create a new place
GET https://dsrroahuziyleoxdzyps.supabase.co/rest/v1/tasks
Content-Type: application/json
apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzcnJvYWh1eml5bGVveGR6eXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NjQyODEsImV4cCI6MjA3MTU0MDI4MX0.WLzdADgy9o6PDP6g8yMdFB3S9dbuxhLxgwjfmNoL8Uk



### Create a new place
POST http://localhost:3000/places
Content-Type: application/json

{
  "name": "Eiffel Tower",
  "location": "Paris, France",
  "year_built": 1889
}

### Read all places
GET http://localhost:3000/places

### Read a single place by ID
GET http://localhost:3000/places/1

### Update a place by ID
PUT http://localhost:3000/places/1
Content-Type: application/json

{
  "name": "Eiffel Tower",
  "location": "Paris, France",
  "year_built": 1889,
  "description": "Iconic landmark in Paris"
}

### Delete a place by ID
DELETE http://localhost:3000/places/1