export const FETCH_PLACES = "FETCH_PLACES" as const;
export const FETCH_PLACES_SUCCESS = "FETCH_PLACES_SUCCESS" as const;
export const FETCH_PLACES_FAILURE = "FETCH_PLACES_FAILURE" as const;

export const FETCH_PLACE_DETAIL = "FETCH_PLACE_DETAIL" as const;
export const FETCH_PLACE_DETAIL_SUCCESS = "FETCH_PLACE_DETAIL_SUCCESS" as const;
export const FETCH_PLACE_DETAIL_FAILURE = "FETCH_PLACE_DETAIL_FAILURE" as const;
