export const FETCH_PLACES = "FETCH_PLACES" as const;
export const FETCH_PLACES_SUCCESS = "FETCH_PLACES_SUCCESS" as const;
export const FETCH_PLACES_FAILURE = "FETCH_PLACES_FAILURE" as const;

export const FETCH_PLACE_DETAIL = "FETCH_PLACE_DETAIL" as const;
export const FETCH_PLACE_DETAIL_SUCCESS = "FETCH_PLACE_DETAIL_SUCCESS" as const;
export const FETCH_PLACE_DETAIL_FAILURE = "FETCH_PLACE_DETAIL_FAILURE" as const;

export const UPDATE_PLACE_VISITED = "UPDATE_PLACE_VISITED" as const;
export const UPDATE_PLACE_VISITED_SUCCESS =
  "UPDATE_PLACE_VISITED_SUCCESS" as const;
export const UPDATE_PLACE_VISITED_FAILURE =
  "UPDATE_PLACE_VISITED_FAILURE" as const;

export const FETCH_VISITED_PLACES = "FETCH_VISITED_PLACES" as const;
export const FETCH_VISITED_PLACES_SUCCESS =
  "FETCH_VISITED_PLACES_SUCCESS" as const;
export const FETCH_VISITED_PLACES_FAILURE =
  "FETCH_VISITED_PLACES_FAILURE" as const;
